Update setup_server.bat
mdnoble73/aspen-discovery pull request #1248
Opened 2023-06-27 19:08 UTC by NashvillePublicLibrary

2023-06-28 14:47 UTC, mdnoble73 requested changes

2023-06-28 14:47 UTC, mdnoble73 commented on setup_server.bat
> +echo Include "c:/web/aspen-discovery/sites/nashville.aspenlocal/httpd-nashville.aspenlocal.conf"
This needs to be parameterized

2023-06-28 14:47 UTC, mdnoble73 commented on setup_server.bat
> +set HOST=%1
Let's leave this SERVERNAME for consistency with other setup files

2023-06-28 23:31 UTC, NashvillePublicLibrary commented on setup_server.bat
> +echo Include "c:/web/aspen-discovery/sites/nashville.aspenlocal/httpd-nashville.aspenlocal.conf"
Because createSite.php already instructs user to insert the Include statement, I just made the whole mess a comment in the Windows setup server batch file. Zehr gut?

2023-07-03 18:49 UTC, mdnoble73 commented
We reviewed and decided these scripts are no longer needed

2023-07-03 18:49 UTC, closed without merging