Cookie consent
mdnoble73/aspen-discovery pull request #1289
Opened 2023-07-18 10:25 UTC by Jacobomara901

This patch adds a Cookie consent banner for GDPR purposes. It can be toggled on under system variables and additionally allows you to add your cookie policy as html to be displayed when the user requests more information.

Test plan:
 - Log in as aspen_admin user
 - Navigate to system variables in the administration menu
 - Click edit and scroll to bottom
 - Notice new data protection section and toggle cookie consent on. Save changes.
 - *New cookie consent banner should now appear*
 - Set new cookie policy HTML in same section of system variables.
 - Notice these changes are shown when more information is requested on the cookie consent banner
 - Accept cookies and check cookie is assigned correctly in browser dev tools.
 - Check that IP storage checkbox still works as intended in new data protection section, then navigating to "Usage by IP" in the administration section.
When checked: IP addresses should be listed.
When not checked: This page should not list any IP addresses

2023-07-18 23:53 UTC, catsoup11789 requested changes

2023-07-18 23:53 UTC, catsoup11789 commented on code/web/sys/DBMaintenance/version_updates/23.07.00.php
Can you move these db changes to the 23.08.00 file?

2023-07-26 16:48 UTC, Jacobomara901 commented
Hey, sorry for the delay on this! 
Changes for 23.08.00.php are at the top of the file as I was tracking 23.07.00 and thought this would be the easiest fix in terms of merge conflicts. If you'd prefer something different next time please let me know and I will pass it on to the rest of the team on this end

2023-07-31 22:24 UTC, mdnoble73 requested changes

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/index.php
> +	AspenError::raiseError("Error loading cookie consent banner");
Rather than raising an error here, let's just leave the default.  This shouldn't get triggered, but could if the system variables table hasn't been created yet.

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +                <span>We use cookies on this site to enhance your user experience.</span>
This needs to be translatable

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +                <abbr>By clicking any link on this website, you are giving us consent to set and store cookies.</abbr>
Is abbr the correct tag for this? I don't think the semantics are quite right here? Also needs translation.

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +                <a href="#" id="consentAgree" class="button">Yes, I agree</a>
Needs translation

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +                <a href="#" id="consentDisagree" class="button">No, I want to find out more</a>
Needs translation, how are we providing more info? I don't see it yet, but also haven't read all the way through the code

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +    <link rel="stylesheet" href="/interface/themes/responsive/css/cookie-consent.css" />
The CSS should all get merged into the main.css file which we build using a File Watcher in PHP Storm so you shouldn't need to include the file separately.

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +    <script>cookiePolicyHTML='{$cookieStorageConsentHTML|escape:javascript|regex_replace:"/[\r\n]/" : " "}'</script>
This will want to be defined in globals.js and then set in cssAndJsIncludes

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +    <script src="/interface/themes/responsive/js/aspen/cookieConsent.js"></script>
This will get merged into aspen.js. The merge is done as part of merge_javascript.php so it won't need to get inserted here

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/css/cookie-consent.less
> +    .btnWrap{
I don't think we want to override .btnWrap here. It's probably better to give it a new class with the customizations needed and even with that we should think about why we want to override them from the defaults

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/css/cookie-consent.less
> +*{
Overriding this for everything will probably cause lots of layout errors

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +                <a href="#" id="consentAgree" class="button">Yes, I agree</a>
These buttons will need translations. Also stylistically, we tend to have these provide onclick handlers in the .tpl file for clarity.

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +    <script>cookiePolicyHTML='{$cookieStorageConsentHTML|escape:javascript|regex_replace:"/[\r\n]/" : " "}'</script>
This will want to be defined in globals.js and then can be updated in cssAndJsIncludes

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +    <link rel="stylesheet" href="/interface/themes/responsive/css/cookie-consent.css" />
This should be included as part of the main.css file that we merge with a PHPStorm file watcher

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/interface/themes/responsive/js/aspen/cookieConsent.js
> +$(document).ready(function () {
These should get merged into the aspen.js file using merge_javascript.php so they can be called with onclick handlers within the tpl.

2023-07-31 22:24 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/23.08.00.php
> +				"UPDATE system_variables set cookiePolicyHTML = 'This body has not yet set a cookie storage policy, please check back later.'",
Let's run the default text by Jordan to see what she thinks

2023-08-02 17:12 UTC, Jacobomara901 commented on code/web/index.php
> +	AspenError::raiseError("Error loading cookie consent banner");
Removed the raising of AspenError

2023-08-02 17:13 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +                <abbr>By clicking any link on this website, you are giving us consent to set and store cookies.</abbr>
You are correct i believe, I've changed this to a small instead.

2023-08-02 17:13 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +                <span>We use cookies on this site to enhance your user experience.</span>
Added

2023-08-02 17:13 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +                <a href="#" id="consentAgree" class="button">Yes, I agree</a>
Added

2023-08-02 17:14 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +                <a href="#" id="consentDisagree" class="button">No, I want to find out more</a>
Translation added. Was originally using jquery for an onclick check which presented with an aspen modal populated with the html set in sysvars

2023-08-02 17:15 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +                <a href="#" id="consentDisagree" class="button">No, I want to find out more</a>
should now be more stylistically cohesive with other areas of aspen

2023-08-02 17:15 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +    <script>cookiePolicyHTML='{$cookieStorageConsentHTML|escape:javascript|regex_replace:"/[\r\n]/" : " "}'</script>
both have now been added

2023-08-02 17:15 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/css/cookie-consent.less
> +    .btnWrap{
You are correct, overriding is in fact not necessary at all so the css has been removed.

2023-08-02 17:19 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +    <link rel="stylesheet" href="/interface/themes/responsive/css/cookie-consent.css" />
This has now been done (though just using lessc manually as we do not currently use phpstorm) I couldn't see any issues with the command but if there are any please let me know and I will amend.

2023-08-02 17:20 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +    <script src="/interface/themes/responsive/js/aspen/cookieConsent.js"></script>
The above has now been merged in to aspen.js and the amalgamated file has been added to the refactor commit.

2023-08-02 17:21 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +                <a href="#" id="consentAgree" class="button">Yes, I agree</a>
onclick handlers have been added instead and translations added also.

2023-08-02 17:21 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +    <link rel="stylesheet" href="/interface/themes/responsive/css/cookie-consent.css" />
Added to main.css and removed from the .tpl file

2023-08-02 17:21 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +    <script>cookiePolicyHTML='{$cookieStorageConsentHTML|escape:javascript|regex_replace:"/[\r\n]/" : " "}'</script>
both have now been added.

2023-08-02 17:22 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/js/aspen/cookieConsent.js
> +$(document).ready(function () {
as above, this has now been amended.

2023-08-02 17:22 UTC, Jacobomara901 commented on code/web/sys/DBMaintenance/version_updates/23.08.00.php
> +				"UPDATE system_variables set cookiePolicyHTML = 'This body has not yet set a cookie storage policy, please check back later.'",
Agreed, can be added to the list for Monday. as such, I have not changed this with the rebase commit.

2023-08-02 22:14 UTC, mdnoble73 requested changes
A couple files are replacing the previous version.  Can you fix those and also remove the extra import?

2023-08-02 22:14 UTC, mdnoble73 commented on code/web/release_notes/23.08.00.MD
It looks like this replaced the previous file. I can manually merge, but would be better if your PR had the file with changes from everyone else.

2023-08-02 22:14 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/23.08.00.php
It looks like this replaced the previous file. I can manually merge, but would be better if your PR had the file with changes from everyone else.

2023-08-02 22:14 UTC, mdnoble73 commented on code/web/interface/themes/responsive/css/cookie-consent.less
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;400;700&display=swap');
This import should not be needed

2023-08-02 22:40 UTC, mdnoble73 requested changes
We need to do a bit more with the theming for this, let's target getting it into 23.09 once we get that branch going rather than pushing it into 23.08 since that is due for demo tomorrow.

2023-08-02 22:40 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +{if !$smarty.cookies.cookieConsent}
This is generating a notice.  You should be able to check 
if empty($smarty.cookies.cookieConsent)

2023-08-02 22:40 UTC, mdnoble73 commented on code/web/interface/themes/responsive/css/cookie-consent.less
The default styling on this is generating white buttons on a white bar within a larger blue bar so the text and buttons aren't readable.  We're going to need to see if we can use existing colors from the theme for the buttons and we'll need to make the foreground and background of the consent bar able to be controlled by the theme.

2023-08-03 11:21 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +{if !$smarty.cookies.cookieConsent}
I've replaced the above

2023-08-03 11:23 UTC, Jacobomara901 commented on code/web/interface/themes/responsive/css/cookie-consent.less
This should now be fixed, my .container class was being overridden by the theming. Now replaced with a new classname.

2023-08-03 11:29 UTC, Jacobomara901 commented
Hi Mark, thanks for looking back over this. I've taken a quick look this morning and will separate the theming integration in to a separate PR to follow shortly. How would you suggest I go about adding the integration to themes? From my understanding: I could add it to the theme.css.tpl file, use jquery/selectors or use the getDefaultColor method from admin.js. Let me know what youd prefer and i'll get it over to you asap

2023-08-03 14:17 UTC, mdnoble73 approved these changes

2023-08-03 14:17 UTC, merged