self check changes, api changes
mdnoble73/aspen-discovery pull request #1335
Opened 2023-08-12 20:41 UTC by catsoup11789

2023-08-13 10:35 UTC, mdnoble73 requested changes
Can you take a look at setting the minimum date for the cancellation date again?

2023-08-13 10:35 UTC, mdnoble73 commented on code/web/interface/themes/responsive/Record/hold-popup.tpl
> +							<input type="date" name="cancelDate" id="cancelDate" placeholder="mm/dd/yyyy" value="{$smarty.now|date_format:"%Y-%m-%d"}" class="form-control" size="10" min="{$smarty.now|date_format:"%Y-%m-%
Do we want to provide a default date here?  I think that might break things since we handle the blank date in other places.

2023-08-13 10:35 UTC, mdnoble73 commented on code/web/interface/themes/responsive/Record/hold-popup.tpl
> +							<input type="date" name="cancelDate" id="cancelDate" placeholder="mm/dd/yyyy" value="{$smarty.now|date_format:"%Y-%m-%d"}" class="form-control" size="10" min="{$smarty.now|date_format:"%Y-%m-%
Can we just set a min value here instead?

2023-08-13 14:34 UTC, catsoup11789 commented on code/web/interface/themes/responsive/Record/hold-popup.tpl
> +							<input type="date" name="cancelDate" id="cancelDate" placeholder="mm/dd/yyyy" value="{$smarty.now|date_format:"%Y-%m-%d"}" class="form-control" size="10" min="{$smarty.now|date_format:"%Y-%m-%
When I didn't set a default value, the date validation didn't like the values provided because it comes across as an invalid value if something isn't provided for every part (ie they leave everything as-is but only modify the "day" value) and then wouldn't properly reset; still allowing them to enter the invalid date.

2023-08-13 16:50 UTC, catsoup11789 commented on code/web/interface/themes/responsive/Record/hold-popup.tpl
> +							<input type="date" name="cancelDate" id="cancelDate" placeholder="mm/dd/yyyy" value="{$smarty.now|date_format:"%Y-%m-%d"}" class="form-control" size="10" min="{$smarty.now|date_format:"%Y-%m-%
I definitely see the issue with having a date by default if they don't want to have a hold cancelation date. Maybe we add a checkbox to enable/disable the date field?

2023-08-13 16:53 UTC, catsoup11789 commented on code/web/interface/themes/responsive/Record/hold-popup.tpl
> +							<input type="date" name="cancelDate" id="cancelDate" placeholder="mm/dd/yyyy" value="{$smarty.now|date_format:"%Y-%m-%d"}" class="form-control" size="10" min="{$smarty.now|date_format:"%Y-%m-%
We can also disable keyboard interactions with the field to force use of the date picker --- but I'm not sure about accessibility implications this may have.

2023-08-13 23:16 UTC, mdnoble73 commented on code/web/interface/themes/responsive/Record/hold-popup.tpl
> +							<input type="date" name="cancelDate" id="cancelDate" placeholder="mm/dd/yyyy" value="{$smarty.now|date_format:"%Y-%m-%d"}" class="form-control" size="10" min="{$smarty.now|date_format:"%Y-%m-%
I'll check with Jordan to see what she thinks. We might need to validate things server side and just come back with an error message. I'm guessing this doesn't really happen in practice so we don't want to make it harder for normal usage.

2023-08-13 23:28 UTC, catsoup11789 commented on code/web/interface/themes/responsive/Record/hold-popup.tpl
> +							<input type="date" name="cancelDate" id="cancelDate" placeholder="mm/dd/yyyy" value="{$smarty.now|date_format:"%Y-%m-%d"}" class="form-control" size="10" min="{$smarty.now|date_format:"%Y-%m-%
@mdnoble73 I went ahead and just commented out these changes so that I can get the other changes in to continue work on other things tomorrow.

2023-08-14 13:06 UTC, mdnoble73 commented on code/web/interface/themes/responsive/Record/hold-popup.tpl
> +							<input type="date" name="cancelDate" id="cancelDate" placeholder="mm/dd/yyyy" value="{$smarty.now|date_format:"%Y-%m-%d"}" class="form-control" size="10" min="{$smarty.now|date_format:"%Y-%m-%
Talked with Jordan today and she was thinking that it's best to leave the field with a blank value and then on the server side we can validate that the date is in the future.  If it's in the past we can just return an error message and they can resubmit.  That is probably the least amount of disruption to the normal workflow.

2023-08-14 13:58 UTC, catsoup11789 commented on code/web/interface/themes/responsive/Record/hold-popup.tpl
> +							<input type="date" name="cancelDate" id="cancelDate" placeholder="mm/dd/yyyy" value="{$smarty.now|date_format:"%Y-%m-%d"}" class="form-control" size="10" min="{$smarty.now|date_format:"%Y-%m-%
Can you go ahead and merge the commented code for now so I can finish working on self-check stuff? I will revisit the validation later.

2023-08-14 21:03 UTC, catsoup11789 commented on code/web/interface/themes/responsive/Record/hold-popup.tpl
> +							<input type="date" name="cancelDate" id="cancelDate" placeholder="mm/dd/yyyy" value="{$smarty.now|date_format:"%Y-%m-%d"}" class="form-control" size="10" min="{$smarty.now|date_format:"%Y-%m-%
Re-worked this so it checks the date when processing submitHoldForm.

2023-08-18 18:35 UTC, mdnoble73 approved these changes

2023-08-18 18:37 UTC, merged