Events Updates Progress
mdnoble73/aspen-discovery pull request #1342
Opened 2023-08-21 15:41 UTC by K-Alette

3 new files:
services\Events\EventsFacets.php
sys\Events\EventsFacet.php
sys\Events\EventsFacetGroup.php

2 Edited:
sys\Account\User.php - Add section for Event Facet Settings in Admin sys\SearchObject\EventsSearcher.php - Update how we search with facets for events (note, this does not work at all yet)

23.08.00.php updates:
--Add permissions for editing events facets
--Add table for Events Facets

2023-08-21 23:24 UTC, mdnoble73 requested changes
Just getting some initial comments in

2023-08-21 23:24 UTC, mdnoble73 commented on code/web/services/Events/EventsFacets.php
> +			$groupedWorkDisplaySettings = new GroupedWorkDisplaySetting();
WE probably need to update to use EventsFacetGroup here

2023-08-21 23:24 UTC, mdnoble73 commented on code/web/services/Events/EventsFacets.php
> +            $eventsFacetSetting->find(true);
We should check here that we get an actual response 
if (->find(true)){
...

2023-08-21 23:24 UTC, mdnoble73 commented on code/web/sys/Account/User.php
> +			$sections['events']->addAction(new AdminAction('Event Facet Settings', 'Define facets for event searches.', '/Events/EventsFacets'), 'Administer Events Facet Settings');
Check with Jordan to see if we need another permission to only administer events for the user's home library

2023-08-21 23:24 UTC, mdnoble73 commented on code/web/sys/Events/EventsFacetGroup.php
> +			'onClick' => "return AspenDiscovery.Admin.showCopyFacetGroupForm('$this->id')",
This probably doesn't work now.  If it doesn't, we can remove.

2023-08-21 23:24 UTC, mdnoble73 commented on code/web/sys/Events/LibraryEventsSetting.php
We can drop this entire class and just connect the group to the library directly

2023-08-21 23:24 UTC, mdnoble73 commented on code/web/sys/SearchObject/EventsSearcher.php
> +            $eventsFacetSetting = new LibraryEventsSetting();
This will be querying the EventsFacetGroup which connects to the library

2023-08-22 16:15 UTC, K-Alette commented on code/web/sys/Events/LibraryEventsSetting.php
I'd rather not mess with that rn, it will break other things to get rid of it :/

2023-08-22 16:16 UTC, K-Alette commented on code/web/sys/Account/User.php
> +			$sections['events']->addAction(new AdminAction('Event Facet Settings', 'Define facets for event searches.', '/Events/EventsFacets'), 'Administer Events Facet Settings');
Jordan said to wait on this for now

2023-08-22 16:24 UTC, mdnoble73 approved these changes

2023-08-22 16:25 UTC, merged