23.09.00 e commerce
mdnoble73/aspen-discovery pull request #1365
Opened 2023-08-24 02:09 UTC by tnlibrarian

2023-08-24 16:20 UTC, mdnoble73 requested changes
Looking good, just a little cleanup!

2023-08-24 16:20 UTC, mdnoble73 commented on code/web/interface/themes/responsive/Admin/propertiesListCSV.tpl
> +{*
Let's remove this commented out bit

2023-08-24 16:20 UTC, mdnoble73 commented on code/web/services/Admin/DonationsReport.php
> +            $locationList = Location::getLocationListAsObjects(true);
We should be able to optimize this with a ->whereAddIn($listOfLocations) where $listOfLocations is the locations for the library

2023-08-24 16:20 UTC, mdnoble73 commented on code/web/services/Admin/ObjectEditor.php
> +                foreach ($_REQUEST['selectedObject'] as $k=>$v) {
This needs to check to see if anything has been selected using isset or empty to see if selectedObjects have been passed.

2023-08-24 16:20 UTC, mdnoble73 commented on code/web/services/Admin/eCommerceReport.php
> +            $homeLibrary = Library::getPatronHomeLibrary()->libraryId;
This might be able to be simplified?

2023-08-24 16:22 UTC, mdnoble73 commented
nitial review comments: 
- All reports are downloaded with the name DonationsReport.csv, we should pass that from the ObjectEditor maybe based on the page title for the active editor? 
- If no rows are selected, there are 2 notices that get displayed.  We should either catch this with JavaScript (best) or process everything if nothing is selected, might need to check with Jordan. 
- Should we always always quote values? Right now some are quoted and some aren't
- Can you reformat with code styles so tabs etc at start of line are correct

2023-08-24 16:26 UTC, tnlibrarian commented on code/web/interface/themes/responsive/Admin/propertiesListCSV.tpl
> +{*
d'oh!

2023-08-25 17:20 UTC, tnlibrarian commented on code/web/services/Admin/ObjectEditor.php
> +                foreach ($_REQUEST['selectedObject'] as $k=>$v) {
https://github.com/tnlibrarian/aspen-discovery/commit/5a6b2747b1b4b2e782fb6da7cb74a474ac471e78

2023-08-25 19:56 UTC, mdnoble73 approved these changes

2023-08-25 19:56 UTC, mdnoble73 commented on code/web/services/Admin/eCommerceReport.php
> +            $homeLibrary = Library::getPatronHomeLibrary()->libraryId;
Nevermind

2023-08-25 19:56 UTC, merged