Feat: List author control
mdnoble73/aspen-discovery pull request #1444
Opened 2023-10-10 16:39 UTC by AlexanderBlanchardAC

Test Plan:
Log in to Aspen and create two new lists note that you now have the ability to decide whether to display your name or not. (If lists are set to public).
Ensure both lists are public and searchable. Enable "display list author" on one list and not on the other one. If you have chosen to share your name, a badge stating “display list author” will be at the bottom of your list along with the “searchable” and “public” badges.

Add at least three items to each list.
Search lists again and note that your username will appear on the list for which "display list author" is enabled, but on the list for which it is disabled, your name should not appear, you should see, "Created By: Anonymous."

**It may take time for the lists to appear when searched as the indexing is currently set to every two minutes**
You will also see that in the facet config, the Created By dropdown will reflect whether or not the author of the list has chosen to share their name.

2023-10-10 18:05 UTC, mdnoble73 commented
Could you resubmit this on 23.11 since 23.10 is so close to release?

2023-10-11 14:45 UTC, AlexanderBlanchardAC commented
> Could you resubmit this on 23.11 since 23.10 is so close to release?

I have changed the db changes to 23.11.00 and also changed the base branch.

2023-10-12 10:06 UTC, AlexanderBlanchardAC commented
Hi Mark, Sorry, the functionality changes are reincluded now.

2023-10-12 16:19 UTC, mdnoble73 requested changes
Let's default the list author display on

2023-10-12 16:19 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/23.08.00.php
> +				'ALTER TABLE  user_list ADD COLUMN displayListAuthor TINYINT(1) DEFAULT 0',
We'll want to default this to 1 to mimic existing functionality

2023-10-12 16:19 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/23.08.00.php
> +				'ALTER TABLE user ADD COLUMN displayListAuthor TINYINT(1) DEFAULT 0',
We'll also want this to default on to mimic existing functionality

2023-10-12 16:19 UTC, mdnoble73 commented on code/user_list_indexer/src/com/turning_leaf_technologies/reindexer/UserListIndexer.java
> +				listsStmt = dbConn.prepareStatement("SELECT user_list.id as id, deleted, public, searchable, title, description, user_list.created, dateUpdated, username, firstname, lastname, IF(user_list.displa
I'm wondering if we want this to be coded as Library Staff or as blank so that the results don't show in facets?

2023-10-12 16:19 UTC, mdnoble73 commented on code/user_list_indexer/src/com/turning_leaf_technologies/reindexer/UserListIndexer.java
> +				listsStmt = dbConn.prepareStatement("SELECT user_list.id as id, deleted, public, searchable, title, description, user_list.created, dateUpdated, username, firstname, lastname, IF(user_list.displa
I'm wondering if we want this to be coded as Library Staff or as blank so that the results don't show in facets?

2023-10-12 16:19 UTC, mdnoble73 commented on code/web/interface/themes/responsive/MyAccount/createListForm.tpl
> +					<input type='checkbox' name='displayListAuthor' id='displayListAuthor' data-on-text="{translate text="Yes" isPublicFacing=true}" data-off-text="{translate text="No" isPublicFacing=true}" checked
I think we'll want to default this on.

2023-10-12 16:19 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/23.11.00.php
> +					'ALTER TABLE  user_list ADD COLUMN displayListAuthor TINYINT(1) DEFAULT 0',
Let's default this on to match current behavior

2023-10-12 16:19 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/23.11.00.php
> +					'ALTER TABLE user ADD COLUMN displayListAuthor TINYINT(1) DEFAULT 0',
Let's default this on to match current behavior

2023-10-12 16:19 UTC, mdnoble73 commented on code/web/interface/themes/responsive/MyAccount/list.tpl
> +										<input type='checkbox' name='displayListAuthor' id='displayListAuthor' data-on-text="Yes" data-off-text="No" {if $userList->displayListAuthor == 1}checked{/if}/>
Let's default this on to match current behavior

2023-10-16 09:51 UTC, AlexanderBlanchardAC commented on code/web/sys/DBMaintenance/version_updates/23.08.00.php
> +				'ALTER TABLE  user_list ADD COLUMN displayListAuthor TINYINT(1) DEFAULT 0',
I have updated this to 1

2023-10-16 09:51 UTC, AlexanderBlanchardAC commented on code/web/sys/DBMaintenance/version_updates/23.08.00.php
> +				'ALTER TABLE user ADD COLUMN displayListAuthor TINYINT(1) DEFAULT 0',
I have updated this to 1 as well

2023-10-16 09:54 UTC, AlexanderBlanchardAC commented on code/user_list_indexer/src/com/turning_leaf_technologies/reindexer/UserListIndexer.java
> +				listsStmt = dbConn.prepareStatement("SELECT user_list.id as id, deleted, public, searchable, title, description, user_list.created, dateUpdated, username, firstname, lastname, IF(user_list.displa
Left in for now as discussed - may need to be adjusted at a later date

2023-10-16 09:54 UTC, AlexanderBlanchardAC commented on code/web/interface/themes/responsive/MyAccount/createListForm.tpl
> +					<input type='checkbox' name='displayListAuthor' id='displayListAuthor' data-on-text="{translate text="Yes" isPublicFacing=true}" data-off-text="{translate text="No" isPublicFacing=true}" checked
This defaults to on now as the db is updated.

2023-10-16 09:55 UTC, AlexanderBlanchardAC commented on code/web/interface/themes/responsive/MyAccount/list.tpl
> +										<input type='checkbox' name='displayListAuthor' id='displayListAuthor' data-on-text="Yes" data-off-text="No" {if $userList->displayListAuthor == 1}checked{/if}/>
I have updated this to 1 in the 23.11.00 db

2023-10-16 09:55 UTC, AlexanderBlanchardAC commented on code/web/sys/DBMaintenance/version_updates/23.11.00.php
> +					'ALTER TABLE user ADD COLUMN displayListAuthor TINYINT(1) DEFAULT 0',
updated

2023-10-16 09:55 UTC, AlexanderBlanchardAC commented on code/web/sys/DBMaintenance/version_updates/23.11.00.php
> +					'ALTER TABLE  user_list ADD COLUMN displayListAuthor TINYINT(1) DEFAULT 0',
updated

2023-10-24 10:26 UTC, mdnoble73 approved these changes

2023-10-24 10:32 UTC, merged