API changes
mdnoble73/aspen-discovery pull request #1627
Opened 2024-01-23 19:47 UTC by catsoup11789

2024-01-23 21:42 UTC, mdnoble73 requested changes

2024-01-23 21:42 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Location.php
> +	public $_hours;
We can make this protected, but not public.  If it's public it won't clear automatically.

2024-01-23 23:51 UTC, catsoup11789 commented on code/web/sys/LibraryLocation/Location.php
> +	public $_hours;
when it was public, it returned an error about it being public when trying to forcefully clear it...

2024-01-24 00:09 UTC, mdnoble73 approved these changes

2024-01-24 00:09 UTC, merged