NEW FEAT: RIS Citations
mdnoble73/aspen-discovery pull request #1645
Opened 2024-01-31 15:47 UTC by AlexanderBlanchardAC

Prior to applying the patch, create a list that has at least one item on it.
Click on the list title and note that you have the option to 'Generate Citations' or to 'Export List to CSV.'
The option to generate citations does not include RIS or the ability to export.
Apply the patch and repeat the process.
When you click on your list title you should see the option to 'Export to RIS.'
When you click this button a list will download that shows the items on your list in RIS citation format.
The option to export to RIS is also available at the bottom of the page in the toolbar.

2024-01-31 21:05 UTC, mdnoble73 requested changes
This is a big one! Overall changes look great, mostly stylist changes and some changes in places that may not need changing.  Nice work.

2024-01-31 21:05 UTC, mdnoble73 commented on code/cron/.idea/misc.xml
I think the xml definition should still be here?

2024-01-31 21:05 UTC, mdnoble73 commented on code/oai_indexer/src/com/turning_leaf_technologies/oai/OaiIndexerMain.java
I did some checking and I don't see dc:placeOfPublication in the OAI feeds that we have do you have an example where this shows up?

2024-01-31 21:05 UTC, mdnoble73 commented on code/overdrive_extract/src/com/turning_leaf_technologies/overdrive/ExtractOverDriveInfo.java
I don't see placeOfPublication in the OverDrive Metadata.  Do you have an example record(s) where this is showing?

2024-01-31 21:05 UTC, mdnoble73 commented on code/reindexer/src/com/turning_leaf_technologies/reindexer/HooplaProcessor.java
I don't see placeOfPublication in the Hoopla data, do you have an example of this?

2024-01-31 21:05 UTC, mdnoble73 commented on code/reindexer/src/com/turning_leaf_technologies/reindexer/MarcRecordProcessor.java
> +			placesOfPublication.add(AspenStringUtils.trimTrailingPunctuation(MarcUtil.getFirstFieldVal(record, "008[15-17]")));
I wonder if we want to use the 008 values since they won't integrate well with the other places of publication?  If we do use it shoudl we try to translate it from the 2-3 letter code.

2024-01-31 21:05 UTC, mdnoble73 commented on code/reindexer/src/com/turning_leaf_technologies/reindexer/OverDriveProcessor.java
I don't think OverDrive has place of publication

2024-01-31 21:05 UTC, mdnoble73 commented on code/user_list_indexer/src/com/turning_leaf_technologies/reindexer/UserListSolr.java
User lists shouldn't need place of publication

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +				'property' => 'placeOfPublication',
I think this is a duplicate of the property above (place)

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/RecordDrivers/GroupedWorkDriver.php
> +			$this->marcRecordDriver = new MarcRecordDriver($indexFields);
This isn't going to work since indexFields is a grouped work id and MarcRecordDriver will expect a record ID from the ILS.

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/RecordDrivers/GroupedWorkDriver.php
> +						'text' => 'See individual formats and editions',
Let's make this match the text we use in the other locations.  "Varies, see individual formats and editions"

2024-01-31 21:05 UTC, mdnoble73 commented on data_dir_setup/solr7/grouped_works_v2/conf/schema.xml
> +	<copyField source="placeOfPublication" dest="placeOfPublication"/>
This line isn't needed it would just copy the field to itself

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/sys/UserLists/UserList.php
> +		function getISBNs($text) {
The list itself shouldn't have ISBNs, but I may be misunderstanding too.

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/sys/UserLists/UserList.php
> +	private function formatGroupedWorkCitation($curDoc) {
Can we move this into Grouped Work Driver?

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/sys/SolrConnector/GroupedWorksSolrConnector2.php
> +			case 'placeOfPublication':
Do we want to be able to sort by place of publication?  That doesn't seem like it would get used.

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/sys/SolrConnector/GroupedWorksSolrConnector.php
> +			case 'placeOfPublication':
Do we want to be able to sort by place of publication?  That doesn't seem like it would get used.

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/sys/SearchObject/AbstractGroupedWorkSearcher.php
> +						switch ($format) {
We should figure out a good way to translate these since we'll have a hard time coming up with a hardcoded list that works for everyone.

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/sys/Grouping/GroupedWorkDisplaySetting.php
>  		'showPublicationDetails' => 'Published',
I think the showPublicationDetails already shows publisher, place of publication, and date in one line so this might be redundant.

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/21.08.00.php
We don't need to go back to the old updates, we can just do current version

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/23.11.00.php
We'll want this to go in the version where it gets deployed (24.02)

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/21.07.00.php
No need to update the old updates

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/library_location_updates.php
No need to update the old updates

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/base_updates.php
No need to update the old updates

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/services/API/AnodeAPI.php
We can leave this file unchanged, it's unused

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/release_notes/24.02.00.MD
> +### RIS Citations
Let's add information about the place of publication changes too

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/interface/themes/responsive/RecordDrivers/GroupedWork/result.tpl
> +					{if $alwaysShowSearchResultsMainDetails || $summPubPlace}
It think the $summPubPlace variable doesn't match what is used later.  That is summPubPlaces

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/RecordDrivers/OverDriveRecordDriver.php
OverDrive doesn't have this data so we can just return blank

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/RecordDrivers/MarcRecordDriver.php
> -		return $this->getFieldArray('250');
We can remove some of the commented out code here

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/RecordDrivers/MarcRecordDriver.php
> +		$placesOfPublication =  $this->getFieldArray('260', ['a']);
Do we want to match the logic in the indexer to look at 264 and 260 here?

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/RecordDrivers/MarcRecordDriver.php
> -	function getPlacesOfPublication() {
Is this still used anywhere? Can it be safely deleted?

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/interface/themes/responsive/CloudLibrary/view-title-details.tpl
> +				{implode subject=$recordDriver->getPlacesOfPublication() glue=", "}
Does this switch to show just the place without the date and publisher?

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/interface/themes/responsive/Communico/event.tpl
> +                        <h2>{translate text="Communico Event API response" isPublicFacing=true}</h2>
Is h2 correct here?

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/RecordDrivers/IndexRecordDriver.php
> +			'placesOfPublication' => count($placesOfPublication) > 0 ? $placesOfPublication[0] : null,
Will changing the key here cause issues for other citations?

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/RecordDrivers/GroupedWorkDriver.php
> +	/**
How is table of contents notes being used? Do we need to add something regarding this to the release notes?

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/RecordDrivers/GroupedWorkDriver.php
> +			'placeOfPublication' => $this->getPlacesOfPublication(),
Does changing this key cause issues other places? It also changes from a single value to multiple value

2024-01-31 21:05 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +					'place_of_publication' => $_REQUEST['placeofPublication'],
I think this is already accounted for in publication_place unless the name of the field changed?

2024-02-01 09:48 UTC, AlexanderBlanchardAC commented on code/overdrive_extract/src/com/turning_leaf_technologies/overdrive/ExtractOverDriveInfo.java
You are correct. This seems to be the case for a lot of ebook providers. I have removed the place of publication code.

2024-02-01 09:59 UTC, AlexanderBlanchardAC commented on code/web/RecordDrivers/IndexRecordDriver.php
> +			'placesOfPublication' => count($placesOfPublication) > 0 ? $placesOfPublication[0] : null,
The $pubPlaces sections were commented out in the original code so it shouldn't cause issues. I can rename mine to pubPlaces if you prefer?

2024-02-01 12:12 UTC, AlexanderBlanchardAC commented on code/reindexer/src/com/turning_leaf_technologies/reindexer/OverDriveProcessor.java
You are correct, I have removed this code.

2024-02-01 12:12 UTC, AlexanderBlanchardAC commented on code/web/Drivers/Koha.php
> +				'property' => 'placeOfPublication',
Duplicate code removed

2024-02-01 12:14 UTC, AlexanderBlanchardAC commented on code/web/RecordDrivers/GroupedWorkDriver.php
> +						'text' => 'See individual formats and editions',
Altered to match the text in other locations.

2024-02-01 12:23 UTC, AlexanderBlanchardAC commented on code/web/sys/UserLists/UserList.php
> +		function getISBNs($text) {
This was left over from when I was trying to access the ISBN, but is now not needed as it is accessed through getPrimaryISBN, so I have removed the code

2024-02-01 12:25 UTC, AlexanderBlanchardAC commented on code/web/sys/SolrConnector/GroupedWorksSolrConnector2.php
> +			case 'placeOfPublication':
Very true, I have removed it.

2024-02-01 12:25 UTC, AlexanderBlanchardAC commented on code/web/sys/SolrConnector/GroupedWorksSolrConnector.php
> +			case 'placeOfPublication':
Very true, I have removed it.

2024-02-01 16:04 UTC, mdnoble73 commented on code/web/RecordDrivers/IndexRecordDriver.php
> +			'placesOfPublication' => count($placesOfPublication) > 0 ? $placesOfPublication[0] : null,
Whoops yeah my bad.  No problem just removing it and using placesOfPublication.  That's much easier to read.

2024-02-02 10:30 UTC, AlexanderBlanchardAC commented on code/web/release_notes/24.02.00.MD
> +### RIS Citations
Added a bullet point to the Ris Citations section

2024-02-02 11:27 UTC, AlexanderBlanchardAC commented on code/oai_indexer/src/com/turning_leaf_technologies/oai/OaiIndexerMain.java
I think you are correct and it doesn't, I have removed it.

2024-02-02 11:53 UTC, AlexanderBlanchardAC commented on code/web/RecordDrivers/GroupedWorkDriver.php
> +	/**
This forms the N2 section of the RIS citations. I will add to release notes.

2024-02-02 15:36 UTC, AlexanderBlanchardAC commented on code/reindexer/src/com/turning_leaf_technologies/reindexer/MarcRecordProcessor.java
> +			placesOfPublication.add(AspenStringUtils.trimTrailingPunctuation(MarcUtil.getFirstFieldVal(record, "008[15-17]")));
I have included a function to translate the 2/3 letter codes into the relevant country names.

2024-02-02 17:09 UTC, closed without merging