Tiny MCE Config Changes
mdnoble73/aspen-discovery pull request #497
Opened 2022-02-08 21:53 UTC by sloneccls

As per email with Mark, expanded config options for TinyMCE to allow for more robust editing.

2022-02-08 23:31 UTC, mdnoble73 requested changes
Just a couple updates.  Let us know what you think.

2022-02-08 23:31 UTC, mdnoble73 commented on code/web/interface/themes/responsive/DataObjectUtil/textarea.tpl
> -			'img[class=img-responsive|src|border=0|alt|title|width|height]'
We believe this can be changed to: 
'img[class=img-responsive|*]'

2022-02-08 23:31 UTC, mdnoble73 commented on code/web/interface/themes/responsive/DataObjectUtil/textarea.tpl
> +		valid_elements : "@[id|class|style|title|dir<ltr?rtl|lang|xml::lang],"
We think it's better to leave this as all valid elements (we restrict tags that can be used in system variables).

2022-02-08 23:31 UTC, mdnoble73 commented on code/web/interface/themes/responsive/DataObjectUtil/textarea.tpl
> +		//menubar: '',
Do you need the menubar on?  We think it could be confusing for some of our less experienced users.

2022-02-09 15:11 UTC, sloneccls reviewed
Let me know if I'm understanding the proposed changes correctly. If so, we're testing it out like this now.

2022-02-09 15:11 UTC, sloneccls commented on code/web/interface/themes/responsive/DataObjectUtil/textarea.tpl
> +		//menubar: '',
Oops, didn't really mean to still have that on, but I'm double-checking with my co-worker to make sure that wasn't something she was really needing either.

2022-02-09 15:11 UTC, sloneccls commented on code/web/interface/themes/responsive/DataObjectUtil/textarea.tpl
> -			'img[class=img-responsive|src|border=0|alt|title|width|height]'
If I understood the above counter changes correctly, it seems like keeping the valid elements the same as in the base file, and then changing the extended elements here from `'img[class=img-responsive|src|border=0|alt|title|width|height]'` to `'img[class=img-responsive|*]'`  will probably do for is what we need (in a much cleaner way).

2022-02-09 17:13 UTC, mdnoble73 commented on code/web/interface/themes/responsive/DataObjectUtil/textarea.tpl
> -			'img[class=img-responsive|src|border=0|alt|title|width|height]'
That's correct

2022-02-09 17:14 UTC, mdnoble73 commented on code/web/interface/themes/responsive/DataObjectUtil/textarea.tpl
> +		valid_elements : "@[id|class|style|title|dir<ltr?rtl|lang|xml::lang],"
Correct, thanks

2022-02-09 17:14 UTC, mdnoble73 commented on code/web/interface/themes/responsive/DataObjectUtil/textarea.tpl
> +		//menubar: '',
Thanks

2022-02-09 17:37 UTC, sloneccls reviewed
Changes made

2022-02-10 23:38 UTC, merged