api updates
mdnoble73/aspen-discovery pull request #506
Opened 2022-02-15 20:28 UTC by catsoup11789

2022-02-15 21:34 UTC, mdnoble73 requested changes
Let's drop the files in .tmp and a few other comments below

2022-02-15 21:34 UTC, mdnoble73 commented on code/aspen_app/App.js
> +		dsn: 'https://7fe05c932e2b4fd7b93fa3a0acae0649@o994439.ingest.sentry.io/5952947',
Is it ok for this to be in code?

2022-02-15 21:34 UTC, mdnoble73 commented on code/web/services/API/UserAPI.php
> -			$userData->numHoldsAvailableIls = (int) ($accountSummary->numAvailableHolds == null ? 0 : $accountSummary->numAvailableHolds);
This was probably done for Arlington? Is casting it to an int causing an issue

2022-02-15 21:34 UTC, mdnoble73 commented on code/web/services/API/UserAPI.php
> +			if ($user->getLinkedUsers() != null) {
We probably need a switch for whether or not to include Linked Users.  Arlington handles linked users in a different way in the app so we would want the default off.

2022-02-15 21:34 UTC, mdnoble73 commented on code/web/services/API/UserAPI.php
> +				$numCheckedOut += (int)$overDriveSummary->numCheckedOut;
Similar to above, let's add an option to either include linked user data or not

2022-02-15 21:38 UTC, catsoup11789 commented on code/aspen_app/App.js
> +		dsn: 'https://7fe05c932e2b4fd7b93fa3a0acae0649@o994439.ingest.sentry.io/5952947',
Sentry says DSNs are safe to be in public code, but I'll be reworking this eventually to come from the config file to be able to send errors to different projects for branded apps.

2022-02-15 21:40 UTC, catsoup11789 commented on code/web/services/API/UserAPI.php
> -			$userData->numHoldsAvailableIls = (int) ($accountSummary->numAvailableHolds == null ? 0 : $accountSummary->numAvailableHolds);
(int) was greyed out in phpstorm, like it would never be accessed, but I can add it back in just in case.

2022-02-16 15:23 UTC, mdnoble73 approved these changes

2022-02-16 15:30 UTC, merged