SSO
mdnoble73/aspen-discovery pull request #665
Opened 2022-08-16 12:55 UTC by AndrewIsh

2022-08-17 03:23 UTC, mdnoble73 requested changes
A few things we want to take a look at

2022-08-17 03:23 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +			$postFields = $this->setPostField($postFields, 'userid', $library->useAllCapsWhenSubmittingSelfRegistration);
Do we need to worry about any form of URL hacking so someone could submit a userid / cardnumber to cause issues?

2022-08-17 03:23 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/22.08.00.php
> +		'add_library_sso_config_options' => [
Can we move this into 22.09.00.php?

2022-08-17 03:23 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Library.php
> +	//SSO
We may want to pull this out into it's own settings class to make it easier to manage within a consortium and also keep the size of the library settings down a little.

2022-08-17 03:23 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Library.php
> +	private $curlWrapper;
Let's make this a local variable if we can.

2022-08-17 03:23 UTC, mdnoble73 commented on sites/template.linux/conf/crontab_settings.txt
> +*/15 * * * * root chmod g+rw /data/aspen-discovery/{sitename}/covers/original/*
We'll need to add these into the active crontab as appropriate during upgrade.  There is an example of doing that in 22.08

2022-08-17 03:23 UTC, mdnoble73 commented on sites/template.linux/conf/crontab_settings.txt
> +*/15 * * * * root chmod g+rw /data/aspen-discovery/{sitename}/covers/original/*
Can they run as the aspen user?

2022-08-17 03:23 UTC, mdnoble73 commented on install/upgrade_debian.sh
> +git checkout -b $2
Is this a duplicate of lines 16 & 17? Do we just need to be able to run code before & after the pull? 

We might want to switch to the git checkout -b $2 rather than the git pull everywhere as well.

2022-08-17 03:23 UTC, mdnoble73 commented on install/installer_debian.sh
> +read -p "Configure SAML Single Sign On? (y/N) " SAMLSSO
We'll want to do this as part of the centos installer as well and we will want to figure out how to install it for servers that already have Aspen setup. Maybe as a separate script that the main installer calls?

2022-08-17 08:19 UTC, velvetanchovy commented on install/upgrade_debian.sh
> +git checkout -b $2
Sorry, this one is my fault - a temporary change I made for a specific problem on the dev server which I didn't revert. It can come out

2022-08-30 11:24 UTC, AndrewIsh commented on code/web/sys/DBMaintenance/version_updates/22.08.00.php
> +		'add_library_sso_config_options' => [
Mark G has moved this to `22.09.00.php`

2022-08-30 11:26 UTC, AndrewIsh commented on sites/template.linux/conf/crontab_settings.txt
> +*/15 * * * * root chmod g+rw /data/aspen-discovery/{sitename}/covers/original/*
> We'll need to add these into the active crontab as appropriate during upgrade. There is an example of doing that in 22.08

Mark G has created an `updateCron_22_09.php` which appends to `crontab_settings.txt`

2022-08-30 11:31 UTC, AndrewIsh commented on install/upgrade_debian.sh
> +git checkout -b $2
Mark G has removed this

2022-08-30 13:25 UTC, AndrewIsh commented on code/web/Drivers/Koha.php
> +			$postFields = $this->setPostField($postFields, 'userid', $library->useAllCapsWhenSubmittingSelfRegistration);
I don't think so. We call `selfRegister` from `saml2auth.php` which is the script that the IdP returns the client to post-authentication. `saml2auth.php` checks whether the user attributes have been passed by the IdP prior to proceeding. This way, the `$postFields` associative array in the line you mentioned will only ever be dealing with data supplied by the IdP. A malicious request to `saml2auth.php` would fail due to the mutual trust relationship between Aspen and the IdP.

2022-08-30 13:30 UTC, AndrewIsh commented on code/web/sys/LibraryLocation/Library.php
> +	private $curlWrapper;
OK, done

2022-08-30 13:35 UTC, AndrewIsh commented on code/web/sys/LibraryLocation/Library.php
> +	//SSO
I'm happy to do this but there doesn't seem to be a precedent for it. There are parts that rely on large data structures in that class, such as `$structure`, there's no precedent for portions of that being derived from separate classes. As I say, I'm happy to do it, and set a precedent, I just wanted to check with you that you're happy with that.

2022-08-30 13:46 UTC, AndrewIsh commented on install/installer_debian.sh
> +read -p "Configure SAML Single Sign On? (y/N) " SAMLSSO
Mark has moved the portion of `installer_debian.sh` that set up SSO into its own script `samlsso_installer_debian.sh`, so it can be run on a pre-existing Aspen and will set up the SSO.

As far as the CentOS installer is concerned, I'm just looking into this now. I'm not sure we'll be able to install SimpleSAML as a package, as we do with Debian, so it might be a manual process. I'll update here once I've sorted it.

2022-08-30 19:15 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Library.php
> +	//SSO
We do it with things like Grouped Work Display Settings where the bulk of the settings are in a separate table and then we just refer to that table by ID.  It's not critical for initial implementation though.

2022-08-30 19:15 UTC, mdnoble73 commented on install/installer_debian.sh
> +read -p "Configure SAML Single Sign On? (y/N) " SAMLSSO
Thanks, let me know how the investigation goes.

2022-09-01 00:02 UTC, mdnoble73 approved these changes

2022-09-01 00:07 UTC, merged

2022-09-02 13:46 UTC, AndrewIsh commented on install/installer_debian.sh
> +read -p "Configure SAML Single Sign On? (y/N) " SAMLSSO
Thanks Mark. I've now created a CentOS install script for this. I've not been able to test it fully so if you have the ability to test this, it would be very much appreciated. I see you've approved and merged this PR, so I'll create a new one for the outstanding changes.

2022-09-02 13:48 UTC, AndrewIsh commented on code/web/sys/LibraryLocation/Library.php
> +	//SSO
Ah, I completely missed that, sorry for saying there was no precedent there! Is it OK if I leave this for now, we've had some complications at this end that make it hard to test this. I'll definitely come back to this!