Debian Installer Updates take 2
mdnoble73/aspen-discovery pull request #870
Opened 2022-12-12 12:38 UTC by HitScan

Rather than copying whole files just make the necessary edits or
use partial files for *.d/ style configs. (php and mysql config;
solr security limits)

Simplify installer_debian.sh a little and make it behave better if
run a second time. Also use more portable constructions for some
bash-specific builtins used even though the shebang is #!/bin/sh.
(user / group creation, 'read -p' vs 'printf ; read', path creation
and perms)

Rather than calling a script with a #!/bin/sh shebang as an argument
to bash, just change the shebang to #!/bin/bash. (samlsso_installer_debian.sh)

You can't always assume #!/bin/sh is bash (it isn't on recent Debian,
certainly) so a pass with shellcheck at some point would be a good
idea for most shell scripts.

2022-12-13 20:51 UTC, mdnoble73 requested changes
Some questions and changes in the review comments. Let me know if you have questions. 

- Mark

2022-12-13 20:51 UTC, mdnoble73 commented on data_dir_setup/update_solr_files.sh
> +sudo su solr -c  "/usr/local/aspen-discovery/sites/$1/$1.sh restart"
I updated 23.01 so we can drop the need for sudo here. We already expect the command to be run as root.

2022-12-13 20:51 UTC, mdnoble73 commented on install/installer_debian.sh
> +# Specifically, the abandonware php-mcrypt...
We can probably drop php-mcrypt.  Are there any other php modules that require using the non-standard location?

2022-12-13 20:51 UTC, mdnoble73 commented on install/installer_debian.sh
> +# Necessary or surprise baggage from dragging around an old php.ini?
I'm ok with removing copying the php.ini file, let's remove the comment though.  If there are additional concerns, let me know.

2022-12-13 20:51 UTC, mdnoble73 commented on install/installer_debian.sh
> -apt install -y php7.3-pgsql
It looks like this is no longer installed

2022-12-13 20:51 UTC, mdnoble73 commented on install/installer_debian.sh
> -apt install -y php7.3-ssh2
It looks like this is no longer installed

2022-12-13 20:51 UTC, mdnoble73 commented on install/installer_debian.sh
> -echo "Enter the timezone of the server"
Is there a reason this portion (setting time zone was removed)?

2022-12-13 20:51 UTC, mdnoble73 commented on install/setup_aspen_user_debian.sh
> -groupadd aspen_apache
It looks like adding www-data to the aspen_apache group was removed

2022-12-13 20:52 UTC, mdnoble73 approved these changes

2022-12-14 10:25 UTC, mrenvoize commented on install/installer_debian.sh
> -apt install -y php7.3-pgsql
Do we actually need both mysql and pqsql drivers?  I was surprised to see both installed when reviewing the script a while back, but I've not delved deep enough into the codebase to understand why yet, so took it for what it was.

2022-12-14 10:36 UTC, mrenvoize commented on install/installer_debian.sh
> -mysql_secure_installation
This was probably a bit ptfs-e specific, happy for it's removal, I'll make sure it's just documented at our end to ensure it's run as part of server setups.

2022-12-14 18:51 UTC, mdnoble73 commented on install/installer_debian.sh
> -apt install -y php7.3-pgsql
PGSQL is for connection to Sierra so not needed everywhere, but needed in some cases.

2022-12-19 12:14 UTC, HitScan commented on install/installer_debian.sh
> +# Specifically, the abandonware php-mcrypt...
It doesn't look like Aspen is using php-mcrypt directly at all, but it's used by the PHPExcel (for PDFs) and recaptcha (for mailhide) modules. When I initially tried leaving out Sury's repo I think that was the only package that couldn't be installed.

2022-12-19 12:14 UTC, HitScan commented on install/installer_debian.sh
> +# Necessary or surprise baggage from dragging around an old php.ini?
Sorry, yeah, a few of these comments are me just leaving notes to myself and I forgot to pull them out.

2022-12-19 12:19 UTC, HitScan commented on install/installer_debian.sh
> -apt install -y php7.3-pgsql
Pretty much all of the php modules should still be installed, I just do it all at once instead of one here and one there. If we can get rid of the Sury.org repo I can also drop all of the versioning variable stuff and just default to the packaged versions.

I did intentionally leave out bind9 and bind9utils because that didn't seem to be used anywhere.

2022-12-19 12:25 UTC, HitScan commented on install/installer_debian.sh
> -apt install -y php7.3-ssh2
It does look like I missed php7.3-ssh2, I'll do another pass on the module installation to make sure nothing else was missed.

2022-12-19 13:36 UTC, HitScan commented on install/installer_debian.sh
> -echo "Enter the timezone of the server"
That was me intending to change it to dpkg-reconfigure but forgetting to actually put it in place.

2022-12-19 13:42 UTC, HitScan commented on install/setup_aspen_user_debian.sh
> -groupadd aspen_apache
The usermod -a -G ... line above does that. Param -a "appends" secondary groups and -G is a secondary group to add the user to. I moved things around a little so the aspen_apache group could be added to the aspen user at create time.

2022-12-19 14:09 UTC, HitScan commented on data_dir_setup/update_solr_files.sh
> +sudo su solr -c  "/usr/local/aspen-discovery/sites/$1/$1.sh restart"
I must have just missed that; I'll drop this change

2022-12-19 14:23 UTC, HitScan commented
I've added another commit to address the comments.

2023-01-05 15:57 UTC, mdnoble73 commented on install/installer_debian.sh
> +# Specifically, the abandonware php-mcrypt...
We're going to drop PHPExcel and export to CSV directly so that can be removed. It looks like recaptcha degrades with a warning if mcrypt is not deployed.  We're testing to verify the mailhide is not in use (we don't think it should be)

2023-01-05 15:59 UTC, mdnoble73 commented on install/installer_debian.sh
> -apt install -y php7.3-pgsql
It looks like bind9 and bind9utils are only installed on debian so should be ok to remove them.

2023-01-05 16:09 UTC, mdnoble73 requested changes

2023-01-05 16:09 UTC, mdnoble73 commented on install/installer_debian.sh
> -echo "Enter the timezone of the server"
This needs to be put back in place before I can accept the PR

2023-01-05 21:22 UTC, HitScan commented
Specifically a call to timedatectl or something else? (the mysql_secure_installation call is also still present, just moved down) The "dpkg-reconfigure tzdata" line handles both asking and setting the TZ on Debian. That said, I was mistaken in thinking that using timedatectl doesn't correctly set the TZ permanently so I don't have strong feelings about which way that's handled.

2023-01-09 19:44 UTC, mdnoble73 commented
Can you resubmit with installing PHP 8 rather than PHP 7? 
Thanks!

2023-01-12 13:38 UTC, HitScan commented
By removing all of the version checking stuff and still using Sury's repo we automatically install on php 8.2 on Debian. If Aspen needs a specific php 8 point release I can put some of that back. (I haven't experimented much beyond making sure that the installer works)

2023-01-12 22:30 UTC, mdnoble73 commented
Our servers are running 8.0 in general.  8.2 should work, but we are not testing it specifically at this point. I'll work on getting this merged. Thanks

2023-01-12 22:31 UTC, mdnoble73 commented
Our servers are running 8.0 in general. 8.2 should work, but we are not testing it specifically at this point. I'll work on getting this merged. Thanks

2023-01-12 22:33 UTC, mdnoble73 commented
Do you want to resubmit without the version checking now or for 23.02?

2023-01-18 18:19 UTC, HitScan commented
Yeah, I think just aiming for 23.02.00 is best at this point. I'll default the version to 8.0 so there's still control over what point release is used. That will also allow me to squash the various commits so it's less messy.

2023-01-23 17:54 UTC, HitScan commented
Closing this PR to resume on 23.02.00 in PR 964.

2023-01-23 17:54 UTC, closed without merging