Excel to CSV
mdnoble73/aspen-discovery pull request #925
Opened 2023-01-07 00:18 UTC by K-Alette

Updates the following files to use CSV export instead of excel: -UserList.php
-AbstractGroupedWorkSearcher.php
-GenealogySearcher.php
-ManageRequests.php
-MyAccount/AJAX.php
Will update release notes once all are finished

2023-01-08 22:26 UTC, NashvillePublicLibrary commented
@K-Alette when attempting to Export List to Excel from a User List (in this particular case, my dev at http://james.localhost/MyAccount/MyList/1), I get error

{"success":false,"message":"implode(): Argument #2 ($array) must be of type ?array, string given<br\/>[1094] C:\\web\\aspen-discovery\\code\\web\\sys\\UserLists\\UserList.php<br\/>[1094] C:\\web\\aspen-discovery\\code\\web\\sys\\UserLists\\UserList.php<br\/>[6668] C:\\web\\aspen-discovery\\code\\web\\services\\MyAccount\\AJAX.php<br\/>[15] C:\\web\\aspen-discovery\\code\\web\\JSON_Action.php<br\/>[22] C:\\web\\aspen-discovery\\code\\web\\services\\MyAccount\\AJAX.php<br\/>[739] C:\\web\\aspen-discovery\\code\\web\\index.php"}

2023-01-08 22:30 UTC, NashvillePublicLibrary commented
@K-Alette when performing a blank search against Lists (/Union/Search?view=list&lookfor=&searchIndex=ListsKeyword&searchSource=lists) and attempting to use Search Tools > Export to Excel, the result is a blank window with nothing interesting in response or response headers. [This is also the case in the current PHPExcel-based production code 22.12.00, e.g., at https://catalog.library.nashville.org/Lists/Results?lookfor=&type=ListsKeyword&sort=relevance&view=excel&searchSource=lists

2023-01-08 22:37 UTC, NashvillePublicLibrary commented
Blank search against Library Catalog ( /Union/Search?view=list&showCovers=on&lookfor=&searchIndex=Keyword&searchSource=local ) > Search Tools > Export to Excel appears to work!

Manage Materials Requests ( /MaterialsRequest/ManageRequests ) > Export Selected to Excel appears to work!

(In my current dev, I can't test genealogy)

2023-01-09 14:46 UTC, mdnoble73 requested changes
Take a look at the column creation and double check file names.  Thanks!

2023-01-09 14:46 UTC, mdnoble73 commented on code/web/services/MaterialsRequest/ManageRequests.php
> +			header('Content-Disposition: attachment;filename="UserList.csv"');
Let's change the name here to MaterialRequests.csv

2023-01-09 14:46 UTC, mdnoble73 commented on code/web/services/MaterialsRequest/ManageRequests.php
> +			header('Content-Disposition: attachment;filename="UserList.csv"');
(or somethign similar)

2023-01-09 14:46 UTC, mdnoble73 commented on code/web/services/MyAccount/AJAX.php
> +			if (!$showOut) {
I don't think this is going to work since the key won't be Out. You can try building the headers with something like: 
$headers = [];
$headers[] = 'Title';
...
if ($showOut) {
  $headers[] = 'Out';
}

2023-01-09 14:46 UTC, mdnoble73 commented on code/web/services/MyAccount/AJAX.php
> +				$row = array ($title, $author, $format, $checkoutDate, $dueDate, $Renewed, $waitList, $userName);
Same as above, we'll need to build the arrays and then skip adding the elements we don't want

2023-01-09 14:46 UTC, mdnoble73 commented on code/web/services/MyAccount/AJAX.php
> +					if (!$hasLinkedUsers){
Sames as above, we'll only want to add these to the array if hasLinkedUsers is on

2023-01-09 17:19 UTC, K-Alette commented
@NashvillePublicLibrary  - looks like we never had the functionality to export a list search - I'll add that in for my next push of csv export things, ty!

2023-01-09 19:11 UTC, mdnoble73 approved these changes

2023-01-09 19:11 UTC, merged

2023-01-09 19:55 UTC, NashvillePublicLibrary commented
@K-Alette thank you for fixes so far!

I have pulled to Nashville test. At https://galacto.library.nashville.org/Union/Search?view=list&showCovers=on&lookfor=star&searchIndex=ListsKeyword&searchSource=open_archives > Search Tools > Export to Excel

I see the dropdown gets broken re: css. The offending output (with me on a maintenance IP rendering the Warning)

<a href="<br />
<b>Warning</b>:  Undefined array key " excellink"="" in="" <b="">/usr/local/aspen-discovery/tmp/smarty/compile/b552ff7e72beae93c25b2c5d7def181fdb5d6e12_0.file.search-toolbar.tpl.php on line <b>50</b><br>
<br>
<b>Warning</b>:  Attempt to read property "value" on null in <b>/usr/local/aspen-discovery/tmp/smarty/compile/b552ff7e72beae93c25b2c5d7def181fdb5d6e12_0.file.search-toolbar.tpl.php</b> on line <b>50</b><br>
"&gt;Export To Excel</a>